baseURL = "https://jairoeli.github.io/"
languageCode = "en-us"
title = "Jairo Eli de León"
theme = "colindrake.me"
publishBranch = "master"

[permalinks]
    post = "/post/:title/"
    page = "/page/:title/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = -10
# [[menu.main]]
#     name = "Posts"
#     url = "/post"
[[menu.main]]
    name = "Projects"
    url = "/page/projects/"

[[menu.footer]]
    name = "RSS"
    url = "/post/index.xml"
[[menu.footer]]
    name = "Site Info"
    url = "/page/site-info"
